In [1]:
#Import libraries
import pandas as pd
import os

In [4]:
#Create DataFrame from the CSV
drug_df = pd.read_csv('drug_review_test.csv')
drug_df.head()

,Unnamed: 0,patient_id,drugName,condition,review,rating,date,usefulCount,review_length
0,0,163740,Mirtazapine,depression,"""i've tried a few antidepressants over the yea...",10.0,"February 28, 2012",22,68
1,1,206473,Mesalamine,"crohn's disease, maintenance","""my son has crohn's disease and has done very ...",8.0,"May 17, 2009",17,48
2,2,39293,Contrave,weight loss,"""contrave combines drugs that were used for al...",9.0,"March 5, 2017",35,143
3,3,97768,Cyclafem 1 / 35,birth control,"""i have been on this birth control for one cyc...",9.0,"October 22, 2015",4,149
4,4,208087,Zyclara,keratosis,"""4 days in on first 2 weeks. using on arms an...",4.0,"July 3, 2014",13,60

In [8]:
#Keep relevant columns
drug_review_df = drug_df [['patient_id', 'drugName', 'condition', 'review', 'rating']]
drug_review_df.head()

,patient_id,drugName,condition,review,rating
0,163740,Mirtazapine,depression,"""i've tried a few antidepressants over the yea...",10.0
1,206473,Mesalamine,"crohn's disease, maintenance","""my son has crohn's disease and has done very ...",8.0
2,39293,Contrave,weight loss,"""contrave combines drugs that were used for al...",9.0
3,97768,Cyclafem 1 / 35,birth control,"""i have been on this birth control for one cyc...",9.0
4,208087,Zyclara,keratosis,"""4 days in on first 2 weeks. using on arms an...",4.0

In [9]:
#Rename columns 
drugs_review_df = drug_review_df.rename(columns={
   "patient_id": "patient_id",
    "drugName": "drug_name",
    "condition": "med_condition", 
    "review": "review",
    "rating": "rating"
})

drugs_review_df.head()

,patient_id,drug_name,med_condition,review,rating
0,163740,Mirtazapine,depression,"""i've tried a few antidepressants over the yea...",10.0
1,206473,Mesalamine,"crohn's disease, maintenance","""my son has crohn's disease and has done very ...",8.0
2,39293,Contrave,weight loss,"""contrave combines drugs that were used for al...",9.0
3,97768,Cyclafem 1 / 35,birth control,"""i have been on this birth control for one cyc...",9.0
4,208087,Zyclara,keratosis,"""4 days in on first 2 weeks. using on arms an...",4.0

In [10]:
#Check Data types
drugs_review_df.dtypes

patient_id         int64
drug_name         object
med_condition     object
review            object
rating           float64
dtype: object

In [11]:
#Export as CSV(Removing the index column)
drugs_review_csv = drugs_review_df.to_csv('DrugReview.csv', index=False)